### PR TITLE
HTML: Add HTML elements to Library.HTML and Style w/Bulma

### PR DESCRIPTION
**Pull request by Sashab2400**

### CODE REVIEW

**Comment by Sashab2400** [comment]
https://github.com/c-phelps/cozy-bookshelf/pull/19

**Comment by c-phelps** [comment]
Once we can adjust the HTML to use Bulma classes to match the libraryHTML mockup attached below, it will be good to go.
LibraryMockupv2 drawio

**Review by c-phelps — APPROVED** [review]
Accidentally hit approve, apologies!

**Review by c-phelps — CHANGES_REQUESTED** [review]
Once we can adjust the HTML to use Bulma classes to match the libraryHTML mockup attached below, it will be good to go.
LibraryMockupv2 drawio

**Review by ftek00 — APPROVED** [review]

**Review by c-phelps — APPROVED** [review]
Looking a lot better!

**Pull request merged**
